---
title: "Reading data from the web"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

library(rvest)
library(httr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Scrape a table

I want the first page from this link: http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm

1 - get the html

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)

```

2 - extratc the table(s) : focus on the first one

```{r}
tb_marj = 
  drug_use_html %>% 
  html_nodes(css = "table") %>% 
  first() %>% 
  html_table() %>% 
  slice(-1) %>% 
  as_tibble()

```


## Star Wars Movie Info

I want the data from here: https://www.imdb.com/list/ls070150896/

```{r}
url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(url)

```

Grab elements that I want

```{r}
title_vec = 
  swm_html %>% 
  html_nodes(css = ".lister-item-header a") %>% 
  #just fetch the text
  html_text()

gross_rev_vec = 
  swm_html %>% 
  html_nodes(css = ".text-small:nth-child(7) span:nth-child(5)") %>% 
  html_text()

runtime_vec = 
  swm_html %>% 
  html_nodes(css = ".runtime") %>% 
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    gross_rev = gross_rev_vec,
    runtime = runtime_vec
  )

```

## Get some water data

This is coming from an API

```{r}
#csv format
nyc_water_csv = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content("parsed")

#json format
nyc_water_json = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>% 
  content("text") %>% 
  jsonlite::fromJSON() %>% 
  as_tibble()
```


## Get some brfss data - same process, different data

```{r}
#set up the query perimeter to get all the brfss data
#example -   GET("http://google.com/", path = "search", query = list(q = "ham"))
brfss_2010 = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 150000)) %>% 
  content("parsed")

```
















